# configuration variables for Pico W weather station

# WLAN
WIFI_SSID = "INSERT WIFI SSID"
WIFI_PASSWORD = "INSERT WIFI PASSWORD"

# MQTT
MQTT_SERVER = "INSERT IP MQTT SERVER (SAME NETWORK)"
MQTT_CLIENT_ID = "INSERT CLIENT ID NAME"
MQTT_TOPIC = "weatherstation/bme680"
MQTT_USER = "weatheruser"
MQTT_PASSWORD = "INSERT MQTT PASSWORD"

# Sensors & Reading Interval
SENSOR_I2C_SDA = 4
SENSOR_I2C_SCL = 5
READ_INTERVAL = 60

